# Generated by Django 6.0.1 on 2026-02-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_performance_optimizations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="blog_commen_post_id_0b6431_idx",
            old_name="blog_comment_post_created_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="blog_commen_author__3b9f5c_idx",
            old_name="blog_comment_author_created_idx",
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="blog_post_created_45f0c6_idx",
            old_name="blog_post_created_idx",
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="blog_post_author__418f7f_idx",
            old_name="blog_post_author_created_idx",
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="blog_post_categor_405168_idx",
            old_name="blog_post_category_created_idx",
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="blog_post_publish_a2f496_idx",
            old_name="blog_post_published_created_idx",
        ),
    ]
