# Generated by Django 6.0.1 on 2026-02-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_add_laugh_reaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="Canonical URL if content is republished",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=models.TextField(
                blank=True, help_text="Short summary for previews", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_description",
            field=models.CharField(
                blank=True, help_text="SEO meta description", max_length=160
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
