# Generated by Django 6.0.1 on 2026-02-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_reaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("love", "Love"),
                    ("clap", "Clap"),
                    ("insightful", "Insightful"),
                    ("laugh", "Laugh"),
                ],
                max_length=20,
            ),
        ),
    ]
